name: kiosk_app
description: "A new Flutter project."
publish_to: 'none' # Evita publicar en pub.dev

version: 1.0.0+1

environment:
  sdk: "^3.8.1"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # Iconos de Cupertino (iOS)
  cupertino_icons: ^1.0.8

  # Dependencias de Firebase para la app Kiosk
  firebase_core: ^3.15.0
  cloud_firestore: ^5.6.10
  firebase_auth: ^5.0.0

  # Añadimos QR y envío de email
  qr_flutter: ^4.0.0         # Para generar código QR
  url_launcher: ^6.1.5       # Para abrir mailto: en el navegador o app
  intl: ^0.20.2              # Formateo de fechas y monedas
  provider: ^6.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png
