name: kiosk_app
description: "A new Flutter project."
publish_to: 'none' # Evita publicar en pub.dev

version: 1.0.0+1

environment:
  sdk: "^3.8.1"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # Iconos de Cupertino (iOS)
  cupertino_icons: ^1.0.8

  # Dependencias de Firebase para la app Kiosk
  firebase_core: ^3.15.0
  firebase_auth: ^5.6.2
  cloud_firestore: ^5.6.10
  cloud_functions: ^5.6.1

  # Añadimos QR y envío de email
  qr_flutter: ^4.0.0         # Para generar código QR
  url_launcher: ^6.1.5       # Para abrir mailto: en el navegador o app
  intl: ^0.20.2              # Formateo de fechas y monedas
  provider: ^6.1.2
  lottie: ^2.7.0             # Animaciones Lottie para la página de éxito
  confetti: ^0.7.0           # Animación de confeti en pantalla de éxito
  auto_size_text: ^3.0.0     # Texto escalable automaticamente
  audioplayers: ^6.5.0       # Reproducción de efectos de sonido
  http: ^1.1.0               # Peticiones HTTP
  
  # Dependencias para web (PDF y funcionalidades web)
  pdf: ^3.10.7               # Generación de PDFs
  universal_html: ^2.2.4     # Compatibilidad HTML universal

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.13.1

flutter_icons:
  android: true
  ios: true
  image_path: "assets/logo.png"   # Cambia aquí el nombre si tu logo es diferente

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png
    - assets/success.json
    - assets/sound/start.mp3
