name: kiosk_app
description: "A new Flutter project."
publish_to: 'none' # Evita publicar en pub.dev

version: 1.0.0+1

environment:
  sdk: "^3.8.1"

# Dependencias de tu aplicación
dependencies:
  flutter:
    sdk: flutter

  # Iconos de Cupertino (iOS)
  cupertino_icons: ^1.0.8

  # Dependencias de Firebase para la app Kiosk
  firebase_core: ^2.19.0
  cloud_firestore: ^4.8.3
  firebase_auth: ^4.4.3

# Dependencias solo para desarrollo y testing
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

# Configuración específica de Flutter
flutter:
  uses-material-design: true



