import 'dart:convert';
import 'package:http/http.dart' as http;
import 'package:intl/intl.dart';

/// Servicio directo de SendGrid para envío de emails
/// Conecta directamente con la API de SendGrid sin servidor intermedio
class SendGridDirectService {
  // API Key de SendGrid (configurar como variable de entorno)
  static const String _apiKey = String.fromEnvironment(
    'SENDGRID_API_KEY',
    defaultValue: 'YOUR_SENDGRID_API_KEY_HERE',
  );

  // URL base de la API de SendGrid
  static const String _baseUrl = 'https://api.sendgrid.com/v3';

  // Traducciones para email
  static const Map<String, Map<String, dynamic>> _translations = {
    'es': {
      'subject': 'Meypark - Ticket de Estacionamiento',
      'greeting': 'Estimado cliente,',
      'intro':
          'Hemos procesado exitosamente su pago de estacionamiento. A continuación encontrará los detalles de su ticket:',
      'title': 'Ticket de Estacionamiento',
      'plate': 'Matrícula',
      'zone': 'Zona',
      'start': 'Hora de inicio',
      'end': 'Hora de finalización',
      'duration': 'Duración',
      'price': 'Precio total',
      'method': 'Método de pago',
      'thanks': 'Gracias por elegir Meypark',
      'footer':
          'Este ticket ha sido generado automáticamente por el sistema de gestión de aparcamiento Meypark.',
    },
    'ca': {
      'subject': 'Meypark - Tiquet d\'Aparcament',
      'greeting': 'Estimat client,',
      'intro':
          'Hem processat amb èxit el seu pagament d\'estacionament. A continuació trobarà els detalls del seu tiquet:',
      'title': 'Tiquet d\'Estacionament',
      'plate': 'Matrícula',
      'zone': 'Zona',
      'start': 'Hora d\'inici',
      'end': 'Hora de finalització',
      'duration': 'Durada',
      'price': 'Preu total',
      'method': 'Mètode de pagament',
      'thanks': 'Gràcies per triar Meypark',
      'footer':
          'Aquest tiquet ha estat generat automàticament pel sistema de gestió d\'aparcament Meypark.',
    },
    'en': {
      'subject': 'Meypark - Parking Ticket',
      'greeting': 'Dear customer,',
      'intro':
          'We have successfully processed your parking payment. Below you will find the details of your ticket:',
      'title': 'Parking Ticket',
      'plate': 'Plate',
      'zone': 'Zone',
      'start': 'Start time',
      'end': 'End time',
      'duration': 'Duration',
      'price': 'Total price',
      'method': 'Payment method',
      'thanks': 'Thank you for choosing Meypark',
      'footer':
          'This ticket has been automatically generated by the Meypark parking management system.',
    },
  };

  static Future<bool> sendTicketEmail({
    required String recipientEmail,
    required String plate,
    required String zone,
    required DateTime start,
    required DateTime end,
    required double price,
    required String method,
    String? qrData,
    String? customSubject,
    String? customMessage,
    String locale = 'es',
  }) async {
    try {
      // Detectar idioma
      final lang = _detectLocale(locale);
      final t = _translations[lang] ?? _translations['es']!;

      // Formatear fechas
      final dateFmt = DateFormat('dd/MM/yyyy HH:mm');
      final duration = _formatDuration(start, end);
      final priceFormatted = _formatPrice(price, lang);

      // Crear contenido HTML del email
      final htmlContent = _buildEmailHTML(
        t: t,
        plate: plate,
        zone: zone,
        start: dateFmt.format(start),
        end: dateFmt.format(end),
        duration: duration,
        price: priceFormatted,
        method: _getMethodName(method, lang),
        customMessage: customMessage,
      );

      // Crear contenido de texto plano
      final textContent = _buildEmailText(
        t: t,
        plate: plate,
        zone: zone,
        start: dateFmt.format(start),
        end: dateFmt.format(end),
        duration: duration,
        price: priceFormatted,
        method: _getMethodName(method, lang),
        customMessage: customMessage,
      );

      // Configurar email para SendGrid API
      final emailData = {
        'personalizations': [
          {
            'to': [
              {'email': recipientEmail},
            ],
            'subject': customSubject ?? t['subject'],
          },
        ],
        'from': {'email': 'jbolanos.meypar@gmail.com', 'name': 'Meypark'},
        'content': [
          {'type': 'text/plain', 'value': textContent},
          {'type': 'text/html', 'value': htmlContent},
        ],
      };

      print('📧 SendGrid Direct - Enviando email:');
      print('   Destinatario: $recipientEmail');
      print('   Idioma: $lang');
      print('   Asunto: ${customSubject ?? t['subject']}');

      // Enviar a SendGrid API
      final response = await http
          .post(
            Uri.parse('$_baseUrl/mail/send'),
            headers: {
              'Content-Type': 'application/json',
              'Authorization': 'Bearer $_apiKey',
            },
            body: jsonEncode(emailData),
          )
          .timeout(const Duration(seconds: 30));

      print('📧 SendGrid Direct - Respuesta:');
      print('   Status Code: ${response.statusCode}');
      print('   Body: ${response.body}');

      if (response.statusCode == 202) {
        print('✅ Email enviado exitosamente via SendGrid Direct');
        return true;
      } else {
        print('❌ Error enviando email via SendGrid Direct: ${response.body}');
        return false;
      }
    } catch (e) {
      print('❌ Error en SendGridDirectService: $e');
      return false;
    }
  }

  static String _buildEmailHTML({
    required Map<String, dynamic> t,
    required String plate,
    required String zone,
    required String start,
    required String end,
    required String duration,
    required String price,
    required String method,
    String? customMessage,
  }) {
    return '''
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>${t['title']}</title>
    <style>
        body { font-family: Arial, sans-serif; line-height: 1.6; color: #333; }
        .container { max-width: 600px; margin: 0 auto; padding: 20px; }
        .header { background-color: #E62144; color: white; padding: 20px; text-align: center; border-radius: 8px 8px 0 0; }
        .content { background-color: #f8f9fa; padding: 20px; border-radius: 0 0 8px 8px; }
        .ticket-info { background-color: white; padding: 15px; margin: 15px 0; border-radius: 8px; border-left: 4px solid #E62144; }
        .info-row { display: flex; justify-content: space-between; margin: 8px 0; }
        .label { font-weight: bold; color: #E62144; }
        .footer { margin-top: 20px; padding-top: 15px; border-top: 2px solid #eee; text-align: center; color: #666; font-size: 12px; }
        ${customMessage != null ? '.custom-message { background-color: #e3f2fd; border-left: 4px solid #2196f3; padding: 15px; margin: 15px 0; border-radius: 4px; }' : ''}
    </style>
</head>
<body>
    <div class="container">
        <div class="header">
            <h1>🎫 ${t['title']}</h1>
            <p>Smart Parking Management System</p>
        </div>
        
        <div class="content">
            <p>${t['greeting']}</p>
            <p>${t['intro']}</p>
            
            ${customMessage != null ? '<div class="custom-message"><strong>💬 Mensaje:</strong><br>$customMessage</div>' : ''}
            
            <div class="ticket-info">
                <h3 style="color: #E62144; margin-top: 0;">Detalles del Ticket</h3>
                <div class="info-row">
                    <span class="label">${t['plate']}:</span>
                    <span>$plate</span>
                </div>
                <div class="info-row">
                    <span class="label">${t['zone']}:</span>
                    <span>$zone</span>
                </div>
                <div class="info-row">
                    <span class="label">${t['start']}:</span>
                    <span>$start</span>
                </div>
                <div class="info-row">
                    <span class="label">${t['end']}:</span>
                    <span>$end</span>
                </div>
                <div class="info-row">
                    <span class="label">${t['duration']}:</span>
                    <span>$duration</span>
                </div>
                <div class="info-row">
                    <span class="label">${t['price']}:</span>
                    <span>$price</span>
                </div>
                <div class="info-row">
                    <span class="label">${t['method']}:</span>
                    <span>$method</span>
                </div>
            </div>
            
            <p style="text-align: center; font-size: 18px; color: #E62144; font-weight: bold;">
                ${t['thanks']}
            </p>
        </div>
        
        <div class="footer">
            <p>${t['footer']}</p>
            <p>© ${DateTime.now().year} Meypark</p>
        </div>
    </div>
</body>
</html>
    ''';
  }

  static String _buildEmailText({
    required Map<String, dynamic> t,
    required String plate,
    required String zone,
    required String start,
    required String end,
    required String duration,
    required String price,
    required String method,
    String? customMessage,
  }) {
    final lines = <String>[];

    lines.add(t['title']);
    lines.add('');
    lines.add(t['greeting']);
    lines.add('');
    lines.add(t['intro']);
    lines.add('');

    if (customMessage != null) {
      lines.add('Mensaje: $customMessage');
      lines.add('');
    }

    lines.add('Detalles del Ticket:');
    lines.add('${t['plate']}: $plate');
    lines.add('${t['zone']}: $zone');
    lines.add('${t['start']}: $start');
    lines.add('${t['end']}: $end');
    lines.add('${t['duration']}: $duration');
    lines.add('${t['price']}: $price');
    lines.add('${t['method']}: $method');
    lines.add('');
    lines.add(t['thanks']);
    lines.add('');
    lines.add(t['footer']);
    lines.add('© ${DateTime.now().year} Meypark');

    return lines.join('\n');
  }

  static String _detectLocale(String locale) {
    if (locale.startsWith('ca')) return 'ca';
    if (locale.startsWith('en')) return 'en';
    return 'es';
  }

  static String _formatDuration(DateTime start, DateTime end) {
    final d = end.difference(start);
    final hours = d.inHours;
    final minutes = d.inMinutes % 60;

    if (hours > 0) {
      return '${hours}h ${minutes}min';
    }
    return '${minutes}min';
  }

  static String _formatPrice(double price, String locale) {
    final format = NumberFormat.currency(
      locale: locale,
      symbol: '€',
      decimalDigits: 2,
    );
    return format.format(price);
  }

  static String _getMethodName(String method, String locale) {
    final methods = {
      'es': {
        'card': 'Tarjeta',
        'qr': 'QR Pay',
        'mobile': 'Apple/Google Pay',
        'cash': 'Efectivo',
        'bizum': 'Bizum',
      },
      'ca': {
        'card': 'Targeta',
        'qr': 'QR Pay',
        'mobile': 'Apple/Google Pay',
        'cash': 'Efectiu',
        'bizum': 'Bizum',
      },
      'en': {
        'card': 'Card',
        'qr': 'QR Pay',
        'mobile': 'Apple/Google Pay',
        'cash': 'Cash',
        'bizum': 'Bizum',
      },
    };

    return methods[locale]?[method] ?? method;
  }

  static Future<bool> checkSendGridConfig() async {
    try {
      final response = await http
          .get(
            Uri.parse('$_baseUrl/user/profile'),
            headers: {'Authorization': 'Bearer $_apiKey'},
          )
          .timeout(const Duration(seconds: 10));

      if (response.statusCode == 200) {
        print('✅ SendGrid Direct configurado correctamente');
        return true;
      } else {
        print('❌ Error de configuración de SendGrid Direct: ${response.body}');
        return false;
      }
    } catch (e) {
      print('❌ Error conectando con SendGrid Direct: $e');
      return false;
    }
  }

  static Future<bool> testEmailSending() async {
    try {
      print('🧪 Probando envío directo a SendGrid...');

      final success = await sendTicketEmail(
        recipientEmail: 'test@example.com',
        plate: 'TESTSENDGRID123',
        zone: 'coche',
        start: DateTime.now(),
        end: DateTime.now().add(const Duration(hours: 2)),
        price: 2.50,
        method: 'qr',
        locale: 'es',
      );

      if (success) {
        print('✅ Test de SendGrid Direct exitoso');
        return true;
      } else {
        print('❌ Test de SendGrid Direct fallido');
        return false;
      }
    } catch (e) {
      print('❌ Error en prueba de email: $e');
      return false;
    }
  }
}
